# Generated by Django 3.2 on 2021-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
