# Generated by Django 3.2 on 2021-06-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_cart_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(default=None, to='website.CartEntry'),
        ),
    ]
